### ISSUE TITLE
Any plan to support MySQL8.0?

### ISSUE THREAD

**Issue by marvin263** [jeremycole/innodb_ruby#44]
This great tool works fine for 5.6&5.7, but "innodb_ruby/lib/innodb/index.rb:34:in page': undefined method record_describer=' for #Innodb::Page::FspHdrXdes:0x0000559b2ee52ee0 (NoMethodError)" error raises when work on 8.0.

Is there any plan to support MySQL8.0?

These are detailed stackbacks for 8.0.17 and  8.0.20
> marvin@vm204:thebase/innodb_ruby$ sudo ruby -r rubygems -I lib bin/innodb_space  -s /home/marvin/thebase/mysql-8.0.17/data/ibdata1 system-spaces
name                            pages       indexes     
Traceback (most recent call last):
	14: from bin/innodb_space:1638:in `<main>'
	13: from bin/innodb_space:180:in `system_spaces'
	12: from bin/innodb_space:176:in `block in system_spaces'
	11: from bin/innodb_space:176:in `to_a'
	10: from bin/innodb_space:176:in `each'
	 9: from /home/marvin/thebase/innodb_ruby/lib/innodb/space.rb:341:in `each_index'
	 8: from /home/marvin/thebase/innodb_ruby/lib/innodb/space.rb:321:in `each_index_root_page_number'
	 7: from /home/marvin/thebase/innodb_ruby/lib/innodb/data_dictionary.rb:427:in `each_index_by_space_id'
	 6: from /home/marvin/thebase/innodb_ruby/lib/innodb/data_dictionary.rb:357:in `each_index'
	 5: from /home/marvin/thebase/innodb_ruby/lib/innodb/data_dictionary.rb:324:in `each_record_from_data_dictionary_index'
	 4: from /home/marvin/thebase/innodb_ruby/lib/innodb/data_dictionary.rb:287:in `data_dictionary_index'
	 3: from /home/marvin/thebase/innodb_ruby/lib/innodb/space.rb:312:in `index'
	 2: from /home/marvin/thebase/innodb_ruby/lib/innodb/space.rb:312:in `new'
	 1: from /home/marvin/thebase/innodb_ruby/lib/innodb/index.rb:19:in `initialize'
/home/marvin/thebase/innodb_ruby/lib/innodb/index.rb:34:in `page': undefined method `record_describer=' for #<Innodb::Page::FspHdrXdes:0x0000559b2ee52ee0> (NoMethodError)
marvin@vm204:thebase/innodb_ruby$ sudo ruby -r rubygems -I lib bin/innodb_space  -s /var/lib/mysql/ibdata1 system-spaces
name                            pages       indexes     
Traceback (most recent call last):
	14: from bin/innodb_space:1638:in `<main>'
	13: from bin/innodb_space:180:in `system_spaces'
	12: from bin/innodb_space:176:in `block in system_spaces'
	11: from bin/innodb_space:176:in `to_a'
	10: from bin/innodb_space:176:in `each'
	 9: from /home/marvin/thebase/innodb_ruby/lib/innodb/space.rb:341:in `each_index'
	 8: from /home/marvin/thebase/innodb_ruby/lib/innodb/space.rb:321:in `each_index_root_page_number'
	 7: from /home/marvin/thebase/innodb_ruby/lib/innodb/data_dictionary.rb:427:in `each_index_by_space_id'
	 6: from /home/marvin/thebase/innodb_ruby/lib/innodb/data_dictionary.rb:357:in `each_index'
	 5: from /home/marvin/thebase/innodb_ruby/lib/innodb/data_dictionary.rb:324:in `each_record_from_data_dictionary_index'
	 4: from /home/marvin/thebase/innodb_ruby/lib/innodb/data_dictionary.rb:287:in `data_dictionary_index'
	 3: from /home/marvin/thebase/innodb_ruby/lib/innodb/space.rb:312:in `index'
	 2: from /home/marvin/thebase/innodb_ruby/lib/innodb/space.rb:312:in `new'
	 1: from /home/marvin/thebase/innodb_ruby/lib/innodb/index.rb:19:in `initialize'
/home/marvin/thebase/innodb_ruby/lib/innodb/index.rb:34:in `page': undefined method `record_describer=' for #<Innodb::Page::FspHdrXdes:0x000055f09e3e6db0> (NoMethodError)
marvin@vm204:~/thebase/innodb_ruby$

**Comment by marvin263** [comment]
On MySQL 5.7.30, I still get "lib/innodb/index.rb:34:in `page': undefined method `record_describer=' for #<Innodb::Page:0x000056324fc8ce68> (NoMethodError)"

`sudo ruby -r rubygems -I lib bin/innodb_space  -s ~/thebase/mysql-5.7.30/data/ibdata1 system-spaces`
> ......
 mysql/time_zone_leap_second     6           1           
mysql/time_zone_name            6           1           
mysql/time_zone_transition      6           1           
mysql/time_zone_transition_type 6           1           
sakila/FTS_0000000000000031_0000000000000045_INDEX_16           1           
sakila/FTS_0000000000000031_0000000000000045_INDEX_28           1           
sakila/FTS_0000000000000031_0000000000000045_INDEX_36           1           
sakila/FTS_0000000000000031_0000000000000045_INDEX_46           1           
sakila/FTS_0000000000000031_0000000000000045_INDEX_58           1           
sakila/FTS_0000000000000031_0000000000000045_INDEX_66           1           
sakila/FTS_0000000000000031_BEING_DELETED6           1           
sakila/FTS_0000000000000031_BEING_DELETED_CACHE6           1           
sakila/FTS_0000000000000031_CONFIG6           1           
sakila/FTS_0000000000000031_DELETED6           1           
sakila/FTS_0000000000000031_DELETED_CACHE6           1           
sakila/actor                    7           2           
Traceback (most recent call last):
	39: from bin/innodb_space:1638:in `<main>'
	38: from bin/innodb_space:182:in `system_spaces'
	37: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/system.rb:110:in `each_table_name'
	36: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:335:in `each_table'
	35: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:324:in `each_record_from_data_dictionary_index'
	34: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:168:in `each_record'
	33: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:161:in `each_page_at_level'
	32: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:149:in `each_page_from'
	31: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:161:in `block in each_page_at_level'
	30: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:169:in `block in each_record'
	29: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/page/index.rb:963:in `each_record'
	28: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:170:in `block (2 levels) in each_record'
	27: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:325:in `block in each_record_from_data_dictionary_index'
	26: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:336:in `block in each_table'
	25: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/system.rb:111:in `block in each_table_name'
	24: from bin/innodb_space:186:in `block in system_spaces'
	23: from bin/innodb_space:176:in `block in system_spaces'
	22: from bin/innodb_space:176:in `to_a'
	21: from bin/innodb_space:176:in `each'
	20: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/space.rb:341:in `each_index'
	19: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/space.rb:321:in `each_index_root_page_number'
	18: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:427:in `each_index_by_space_id'
	17: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:357:in `each_index'
	16: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:324:in `each_record_from_data_dictionary_index'
	15: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:168:in `each_record'
	14: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:161:in `each_page_at_level'
	13: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:149:in `each_page_from'
	12: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:161:in `block in each_page_at_level'
	11: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:169:in `block in each_record'
	10: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/page/index.rb:963:in `each_record'
	 9: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:170:in `block (2 levels) in each_record'
	 8: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:325:in `block in each_record_from_data_dictionary_index'
	 7: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:358:in `block in each_index'
	 6: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/data_dictionary.rb:428:in `block in each_index_by_space_id'
	 5: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/space.rb:322:in `block in each_index_root_page_number'
	 4: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/space.rb:342:in `block in each_index'
	 3: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/space.rb:312:in `index'
	 2: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/space.rb:312:in `new'
	 1: from /home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:19:in `initialize'
/home/marvin/thebase/innodb_ruby-master/lib/innodb/index.rb:34:in `page': undefined method `record_describer=' for #<Innodb::Page:0x000056324fc8ce68> (NoMethodError)

**Comment by jeremycole** [comment]
I created a blanket issue for MySQL 8.0 support, so I will consolidate the info and work there: https://github.com/jeremycole/innodb_ruby/issues/97.
